backend:
  name: git-gateway
  branch: main
media_folder: static/article
public_folder: /article
timezone: "Asia/Kolkata"
collections:
  - name: "article"
    label: "Article"
    folder: "content/english/article"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss+05:30" }
      - { label: "Author", name: "author", widget: "string" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: [],
          tagname: "tag",
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          default: [],
          tagname: "category",
        }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Meta Title", name: "meta_title", widget: "string" }
      - { label: "Meta Description", name: "meta_description", widget: "text" }
      - { label: "Meta Keywords", name: "meta_keywords", widget: "list" }
